// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PlayaMagica.Entities.Entities
{
    public partial class tbEncargadosXActividades
    {
        public int enac_Id { get; set; }
        public int? enca_Id { get; set; }
        public int? acti_Id { get; set; }
        public bool? enac_Estado { get; set; }
        public int? enac_UsuarioCreador { get; set; }
        public DateTime? enac_FechaCreacion { get; set; }
        public int? enac_UsuarioModificador { get; set; }
        public DateTime? enac_FechaModificacion { get; set; }

        public virtual tbActividades acti { get; set; }
        public virtual tbEncargados enca { get; set; }
    }
}