// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PlayaMagica.Entities.Entities
{
    public partial class tbMantenimientoXEquipo
    {
        public int maeq_Id { get; set; }
        public int? equi_Id { get; set; }
        public int? mant_Id { get; set; }
        public bool? maeq_Estado { get; set; }
        public int? maeq_UsuarioCreador { get; set; }
        public DateTime? maeq_FechaCreacion { get; set; }
        public int? maeq_UsuarioModificador { get; set; }
        public DateTime? maeq_FechaModificacion { get; set; }

        public virtual tbEquipos equi { get; set; }
        public virtual tbMantenimiento mant { get; set; }
    }
}