// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PlayaMagica.Entities.Entities
{
    public partial class VW_tbDepartamentos
    {
        public string dept_Id { get; set; }
        public string dept_Descripcion { get; set; }
        public int? dept_UsuarioCreador { get; set; }
        public string dept_UsuarioCreador_Nombre { get; set; }
        public DateTime? dept_FechaCreacion { get; set; }
        public int? dept_UsuarioModificador { get; set; }
        public string dept_UsuarioModificador_Nombre { get; set; }
        public DateTime? dept_FechaModificacion { get; set; }
    }
}