// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PlayaMagica.Entities.Entities
{
    public partial class VW_tbMantenimiento
    {
        public int mant_Id { get; set; }
        public string mant_Descricion { get; set; }
        public bool? mant_Estado { get; set; }
        public int? mant_UsuarioCreador { get; set; }
        public string mant_UsuarioCreador_Nombre { get; set; }
        public DateTime? mant_FechaCreacion { get; set; }
        public int? mant_UsuarioModificador { get; set; }
        public string mant_UsuarioModificador_Nombre { get; set; }
        public DateTime? mant_FechaModificacion { get; set; }
    }
}