// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PlayaMagica.Entities.Entities
{
    public partial class VW_tbPlayas
    {
        public int play_Id { get; set; }
        public string play_Playa { get; set; }
        public int? dire_Id { get; set; }
        public string dire_DireccionExacta { get; set; }
        public string play_ImgUrl { get; set; }
        public bool? play_Estado { get; set; }
        public int? play_UsuarioCreador { get; set; }
        public string play_UsuarioCreador_Nombre { get; set; }
        public DateTime? play_FechaCreacion { get; set; }
        public int? play_UsuarioModificador { get; set; }
        public string play_UsuarioModificador_Nombre { get; set; }
        public DateTime? play_FechaModificacion { get; set; }
    }
}