// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PlayaMagica.Entities.Entities
{
    public partial class tbActividades
    {
        public tbActividades()
        {
            tbActividadesXFecha = new HashSet<tbActividadesXFecha>();
            tbEncargadosXActividades = new HashSet<tbEncargadosXActividades>();
            tbEquipoXActividades = new HashSet<tbEquipoXActividades>();
            tbReservaciones = new HashSet<tbReservaciones>();
        }

        public int acti_Id { get; set; }
        public string acti_Nombre { get; set; }
        public int? acti_Cupo { get; set; }
        public decimal? acti_Precio { get; set; }
        public int? play_Id { get; set; }
        public string acti_ImgUrl { get; set; }
        public bool? acti_Estado { get; set; }
        public int? acti_UsuarioCreador { get; set; }
        public DateTime? acti_FechaCreacion { get; set; }
        public int? acti_UsuarioModificador { get; set; }
        public DateTime? acti_FechaModificacion { get; set; }

        public virtual tbUsuarios acti_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios acti_UsuarioModificadorNavigation { get; set; }
        public virtual tbPlayas play { get; set; }
        public virtual ICollection<tbActividadesXFecha> tbActividadesXFecha { get; set; }
        public virtual ICollection<tbEncargadosXActividades> tbEncargadosXActividades { get; set; }
        public virtual ICollection<tbEquipoXActividades> tbEquipoXActividades { get; set; }
        public virtual ICollection<tbReservaciones> tbReservaciones { get; set; }
    }
}