// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PlayaMagica.Entities.Entities
{
    public partial class tbEquipoXActividades
    {
        public int eqac_Id { get; set; }
        public int? acti_Id { get; set; }
        public int? equi_Id { get; set; }
        public int? eqac_UsuarioCreador { get; set; }
        public DateTime? eqac_FechaCreacion { get; set; }
        public int? eqac_UsuarioModificador { get; set; }
        public DateTime? eqac_FechaModificacion { get; set; }


        public virtual tbActividades acti { get; set; }
        public virtual tbUsuarios eqac_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios eqac_UsuarioModificadorNavigation { get; set; }
        public virtual tbEquipos equi { get; set; }
    }
}