// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PlayaMagica.Entities.Entities
{
    public partial class tbFactura
    {
        public int fuct_Id { get; set; }
        public int? rese_Id { get; set; }
        public int? mepa_id { get; set; }
        public decimal? fuct_Subtotal { get; set; }
        public decimal? fuct_Isv { get; set; }
        public decimal? fuct_Total { get; set; }
        public bool? fuct_Estado { get; set; }
        public int? fuct_UsuarioCreador { get; set; }
        public DateTime? fuct_FechaCreacion { get; set; }
        public int? fuct_UsuarioModificador { get; set; }
        public DateTime? fuct_FechaModificacion { get; set; }

        public virtual tbUsuarios fuct_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios fuct_UsuarioModificadorNavigation { get; set; }
        public virtual tbMetodosPago mepa { get; set; }
        public virtual tbReservaciones rese { get; set; }
    }
}