// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PlayaMagica.Entities.Entities
{
    public partial class tbMetodosPago
    {
        public tbMetodosPago()
        {
            tbFactura = new HashSet<tbFactura>();
        }

        public int mepa_id { get; set; }
        public string mepa_Descripcion { get; set; }
        public bool? mepa_Estado { get; set; }
        public int? mepa_UsuarioCreador { get; set; }
        public DateTime? mepa_FechaCreacion { get; set; }
        public int? mepa_UsuarioModificador { get; set; }
        public DateTime? mepa_FechaModificacion { get; set; }

        public virtual tbUsuarios mepa_UsuarioCreadorNavigation { get; set; }
        public virtual tbUsuarios mepa_UsuarioModificadorNavigation { get; set; }
        public virtual ICollection<tbFactura> tbFactura { get; set; }
    }
}