// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PlayaMagica.Entities.Entities
{
    public partial class tbMunicipios
    {
        public tbMunicipios()
        {
            tbDirecciones = new HashSet<tbDirecciones>();
        }

        public string muni_id { get; set; }
        public string muni_Descripcion { get; set; }
        public string dept_id { get; set; }
        public bool? muni_Estado { get; set; }
        public int? muni_UsuarioCreador { get; set; }
        public DateTime? muni_FechaCreacion { get; set; }
        public int? muni_UsuarioModificador { get; set; }
        public DateTime? muni_FechaModificacion { get; set; }

        public virtual tbDepartamentos dept { get; set; }
        public virtual ICollection<tbDirecciones> tbDirecciones { get; set; }
    }
}