// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace PlayaMagica.Entities.Entities
{
    public partial class tbUsuarios
    {
        [NotMapped]
        public string enca_NombreCompleto { get; set; }
        [NotMapped]
        public string role_Descripcion { get; set; }
        public int usua_ID { get; set; }
        public string usua_Usuario { get; set; }
        public string usua_Clave { get; set; }
        public int? usua_EsAdmin { get; set; }
        public int? enca_ID { get; set; }
        public int? role_ID { get; set; }
        public bool? usua_Estado { get; set; }
        public int? usua_UsuarioCreador { get; set; }
        public DateTime? usua_FechaCreacion { get; set; }
        public int? usua_UsuarioModificador { get; set; }
        public DateTime? usua_FechaModificacion { get; set; }
    }
}