// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PlayaMagica.Entities.Entities
{
    public partial class VW_tbActividades
    {
        public int acti_Id { get; set; }
        public string acti_Nombre { get; set; }
        public int? acti_Cupo { get; set; }
        public decimal? acti_Precio { get; set; }
        public string acti_ImgUrl { get; set; }
        public string play_playa { get; set; }
        public int play_id { get; set; }
        public bool? acti_Estado { get; set; }
        public int? acti_UsuarioCreador { get; set; }
        public string acti_UsuarioCreador_Nombre { get; set; }
        public DateTime? acti_FechaCreacion { get; set; }
        public int? acti_UsuarioModificador { get; set; }
        public string acti_UsuarioModificador_Nombre { get; set; }
        public DateTime? acti_FechaModificacion { get; set; }
    }
}