// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PlayaMagica.Entities.Entities
{
    public partial class VW_tbEquipos
    {
        public int equi_Id { get; set; }
        public string equi_Descripcion { get; set; }
        public int? equi_UsoActual { get; set; }
        public int? equi_UsoLimite { get; set; }
        public string equi_ImgUrL { get; set; }
        public bool? equi_Estado { get; set; }
        public int? equi_UsuarioCreador { get; set; }
        public string equi_UsuarioCreador_Nombre { get; set; }
        public DateTime? equi_FechaCreacion { get; set; }
        public int? equi_UsuarioModificador { get; set; }
        public string equi_UsuarioModificador_Nombre { get; set; }
        public DateTime? equi_FechaModificacion { get; set; }
        public string mantenimiento { get; set; }
    }
}