// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PlayaMagica.Entities.Entities
{
    public partial class VW_tbEquipoXActividades
    {
        public int eqac_Id { get; set; }
        public int? acti_Id { get; set; }
        public string acti_Nombre { get; set; }
        public int? equi_Id { get; set; }
        public string equi_Descripcion { get; set; }
        public int? eqac_UsuarioCreador { get; set; }
        public DateTime? eqac_FechaCreacion { get; set; }
        public int? eqac_UsuarioModificador { get; set; }
        public DateTime? eqac_FechaModificacion { get; set; }
    }
}